# -*- coding: utf-8 -*-
"""עותק של Statistics_tests.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zf7OrUMHsV-ViHp99lY_HEiMLkQL4fCi
"""


import numpy as np
import PIL.Image as Image
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras
import tensorflow_hub as hub
from tensorflow.keras.preprocessing import image
import pandas as pd
import os
import xlrd
import math
import scipy
import scipy.stats as stats
import scipy.io.wavfile as wavfile
from scipy.signal import butter, lfilter, freqz
import librosa
import librosa.display
import cv2
import openpyxl
from openpyxl import Workbook

class sample:
  def __init__(self, mother, name, sex, age, matgen, pupgen, rec_num, syls, time_between):
    self.mother = mother
    self.name = name
    self.sex = sex
    self.age = age
    self.matgen = matgen
    self.pupgen = pupgen
    self.rec_num = rec_num
    self.syls = syls
    self.time_between = time_between

samples = np.load('C:\Users\77sha\Desktop\MatPython\model_prediction_recordings_1.npy', allow_pickle=True)

syl_num = []
for i in range(len(samples)):
  for j in range(len(samples[i].syls)):
    if np.max(samples[i].syls[j])<0.5:
      temp = 10
    else:
      temp = np.argmax(samples[i].syls[j])
    samples[i].syls[j] = []
    samples[i].syls[j] = temp
    syl_num.append(samples[i].syls[j])
    print(samples[i].syls[j])


y = 2
workbook = openpyxl.load_workbook('/content/drive/MyDrive/final_project/segmentation/New Segmentatio Data For Final Class_3B.xlsx')
worksheet = workbook.worksheets[0]
worksheet.insert_cols(16)
cell_title = worksheet.cell(row=1, column=16)
cell_title.value = 'Syllable number'
for x in range(len(syl_num)):
    cell_to_write = worksheet.cell(row=y, column=16)
    cell_to_write.value = syl_num[x]
    y += 1
workbook.save('/content/drive/MyDrive/final_project/final_classification/New Segmentatio Data For Final Class_3B.xlsx')
